### ISSUE TITLE
Nature of Visual Images

### ISSUE THREAD

**Issue by ashishkumar822** [water-horse/ICCV2023_SLAM_Challenge#1]
As I have gone through the sequences, I could only find monocular images. Is that so, i.e. does the dataset have only monocular RGB images? I was hoping for stereo images.

**Comment by yuanjun-gao** [comment]
Thank you for the feedback! In order to maintain a consistent format throughout the chosen trajectories within this challenge, the inclusion of stereo RGB images has been omitted. However, rest assured that trajectories comprising stereo images will be released subsequent to the conclusion of the challenge.

Furthermore, it's worth noting that there is a selection of trajectories with both an RGB camera and a thermal camera in the visual-inertial track bonus, which is in the sensor fusion track as well.
