### ISSUE TITLE
about the scenarios

### ISSUE THREAD

**Issue by momoistda** [water-horse/ICCV2023_SLAM_Challenge#37]
Hello,
Thank you very much for your contribution!
I'd like to ask you about the scenarios where your dataset on unmanned ground robots is collected, how many metres wide is the tightest space or underpass roughly?

**Comment by shibowing** [comment]
Hi @momoistda , 
Sorry for the late reply! 
The ground robot is mostly from DARPA SubT challenge. It is mostly subterrean environments. I cannot see how many meteres wide since it varied case by case. However, these are the environments our dataset will cover.
 
![image](https://github.com/user-attachments/assets/4e4e7d51-b7f3-426b-8d05-ccebf3255790)
